### ISSUE TITLE
Graph has an error.

### ISSUE THREAD

**Issue by rahulsayz** [AI-Citizen/SolidGPT#98]
Hi Team,

When ever I tried to onboard a project I get the onboard success
[2023-12-11 19:10:01,589: INFO/MainProcess] Task solidgpt.src.api.celery_tasks.celery_task_onboard_repo_graph[0e3c67f4-1e02-4fc0-b62a-c3d264ff44df] succeeded in 127.07799999997951s: '**-****-****-****-**

However when I start chatting I this error 
    raise ValueError(f"Collection {collection_name} not found")
ValueError: Collection d2d1a8a9-1067-429f-9525-0e6090045e8e not found

Complete log
[2023-12-11 19:10:48,574: WARNING/MainProcess] Directory 'D:\SolidGPT-0.2.7\solidgpt\../localstorage\workspace\out\d32ab2ce-1e97-4447-854c-3aa669a6d8f0\Query_code_0' created.
[2023-12-11 19:10:48,575: WARNING/MainProcess] Directory 'D:\SolidGPT-0.2.7\solidgpt\../localstorage\workspace\out\d32ab2ce-1e97-4447-854c-3aa669a6d8f0\Repo_Chat_1' created.
[2023-12-11 19:10:48,575: INFO/MainProcess] Executing SolidGPT...
[2023-12-11 19:10:48,575: WARNING/MainProcess] Node begins Query code task...
[2023-12-11 19:10:48,577: INFO/MainProcess] Start to search best five code...
[2023-12-11 19:10:49,580: ERROR/MainProcess] Task solidgpt.src.api.celery_tasks.celery_task_repo_chat_graph[56417a7d-fb8c-499f-acd1-e79e375d97c6] raised unexpected: ValueError('Collection d2d1a8a9-1067-429f-9525-0e6090045e8e not found')
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\app\trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\celery\app\trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\SolidGPT-0.2.7\solidgpt\src\api\celery_tasks.py", line 117, in celery_task_repo_chat_graph
    g.execute()
  File "D:\SolidGPT-0.2.7\solidgpt\src\workgraph\workgraph.py", line 115, in execute
    self.__execute_node(node)
  File "D:\SolidGPT-0.2.7\solidgpt\src\workgraph\workgraph.py", line 122, in __execute_node
    node.skill.execute()
  File "D:\SolidGPT-0.2.7\solidgpt\src\workskill\workskill.py", line 52, in execute
    self.execution_impl()
  File "D:\SolidGPT-0.2.7\solidgpt\src\workskill\skills\query_code_local.py", line 51, in execution_impl
    top_five = self.__find_top_five()
  File "D:\SolidGPT-0.2.7\solidgpt\src\workskill\skills\query_code_local.py", line 61, in __find_top_five
    search = self.client.search(
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\qdrant_client\qdrant_client.py", line 315, in search
    return self._client.search(
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\qdrant_client\local\qdrant_local.py", line 154, in search
    collection = self._get_collection(collection_name)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\qdrant_client\local\qdrant_local.py", line 113, in _get_collection
    raise ValueError(f"Collection {collection_name} not found")
ValueError: Collection d2d1a8a9-1067-429f-9525-0e6090045e8e not found

When I checked the UI I can see the message  - "Graph has an error."

Let me know what may be the issue. I am trying to onboard JAVA code base.

**Comment by wwwwww1020** [comment]
Can you try re-onboarding. Seems like onboarding cache file missing

**Comment by rahulsayz** [comment]
Hi,
Even after onboarding again I am still getting the same error.
